---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-labels
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "git@github.com:Speedylo/openstack_auto.git"
    targetRevision: "main"
    path: gitops/manifests/node-labels
    directory: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
