---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:Speedylo/openstack_auto.git
    targetRevision: main
    path: gitops/charts/openstack-helm/mariadb
    helm:
      releaseName: mariadb
      valueFiles:
        - ../values_overrides/mariadb/2025.1-ubuntu_noble.yaml
        - ../../../values/mariadb-local.yaml
      parameters:
        - name: pod.replicas.server
          value: "1"
  destination:
    server: https://kubernetes.default.svc
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
