---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:Speedylo/openstack_auto.git
    targetRevision: main
    path: gitops/charts/openstack-helm/rabbitmq
    helm:
      releaseName: rabbitmq
      valueFiles:
        - ../values_overrides/rabbitmq/2025.1-ubuntu_noble.yaml
      parameters:
        - name: pod.replicas.server
          value: "1"
  destination:
    server: https://kubernetes.default.svc
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
