---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://opendev.org/openstack/openstack-helm.git
      targetRevision: master
      path: rabbitmq
      helm:
        releaseName: rabbitmq
        valueFiles:
          - $upstream/values_overrides/rabbitmq/2025.1-ubuntu_noble.yaml
        parameters:
          - name: pod.replicas.server
            value: "1"
    - repoURL: https://opendev.org/openstack/openstack-helm.git
      targetRevision: master
      ref: upstream
  destination:
    server: https://kubernetes.default.svc
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
