---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glance
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://opendev.org/openstack/openstack-helm.git
      targetRevision: master
      path: glance
      helm:
        releaseName: glance
        valueFiles:
          - $upstream/values_overrides/glance/2025.1-ubuntu_noble.yaml
          - $local/gitops/values/glance-local.yaml
    - repoURL: https://opendev.org/openstack/openstack-helm.git
      targetRevision: master
      ref: upstream
    - repoURL: "{{ GITOPS_REPO_URL }}"
      targetRevision: "{{ GITOPS_REPO_REVISION }}"
      ref: local
  destination:
    server: https://kubernetes.default.svc
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
