---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: libvirt
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "7"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:Speedylo/openstack_auto.git
    targetRevision: main
    path: gitops/charts/openstack-helm/libvirt
    helm:
      releaseName: libvirt
      valueFiles:
        - ../values_overrides/libvirt/2025.1-ubuntu_noble.yaml
      parameters:
        - name: conf.ceph.enabled
          value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
