---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: placement
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "7"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:Speedylo/openstack_auto.git
    targetRevision: main
    path: gitops/charts/openstack-helm/placement
    helm:
      releaseName: placement
      valueFiles:
        - ../values_overrides/placement/2025.1-ubuntu_noble.yaml
        - ../../../values/placement-local.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
