---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: horizon-hook-job-precreate
  namespace: openstack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: horizon-hook-job-precreate
  namespace: openstack
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "create"]
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: horizon-hook-job-precreate
  namespace: openstack
subjects:
  - kind: ServiceAccount
    name: horizon-hook-job-precreate
    namespace: openstack
roleRef:
  kind: Role
  name: horizon-hook-job-precreate
  apiGroup: rbac.authorization.k8s.io
